---
triple:          'arm64-apple-darwin'
binary-path:     '/var/folders/5_/z2vvjg1j6bv1cqdnh4x20wk00000gp/T/rapid-xcframeworks/dd/GoogleUtilities/Build/Intermediates.noindex/ArchiveIntermediates/GULEnvironment/InstallationBuildProductsLocation/usr/local/lib/GULEnvironment.framework/GULEnvironment'
relocations:     []
...
